name: Test python
on:
  pull_request:
    branches:
      - master
      - development
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        py-ver:     # Distro       |  EOL
          - '3.7'   # Debian 10    | 2024-06-30
          - '3.8'   # Ubuntu 20.04 | 2025-04
          - '3.9'   # Debian 11    | 2026-08-31
          - '3.10'  # Ubuntu 22.04 | 2027-04
          - '3.11'  # Debian 12    | 2028-06-30
          - '3.12'  # Ubuntu 24.04 | 2029-04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.py-ver }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py-ver }}

      - name: Install Requirements
        run: python -m pip install tox tox-gh-actions --disable-pip-version-check

      - name: Tox
        run: tox

